version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn -f ScoopShare/pom.xml test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn -f ScoopShare/pom.xml clean package
      - mv ScoopShare/target/ScoopShare-0.0.1-SNAPSHOT.war ScoopShare-0.0.1-SNAPSHOT.war
artifacts:
  files:
    - ScoopShare-0.0.1-SNAPSHOT.war
    - .ebextensions/**/*
eb_codebuild_settings:
  CodeBuildServiceRole: code-build-ScoopShare-build-be-service-role
  ComputeType: BUILD_GENERAL1_SMALL
  Image: aws/codebuild/java:openjdk-8
  Timeout: 60
  base-directory: 'ScoopShare/target/ScoopShare'
